services:

  cath-af-cli:
    image: domain-annotation-pipeline-cath-af-cli
    build: docker/cath-af-cli

  script:
    image: domain-annotation-pipeline-script
    build: docker/script

  ted-tools:
    image: domain-annotation-pipeline-ted-tools
    build: docker/ted-tools